env:
  global:
    - LC_CTYPE=en_US.UTF-8

osx_image: xcode11

branches:
  only:
    - master

matrix:
  include:
    - os: osx
      language: generic
      script:
        - swift --version
        - swift build
        - swift test
      env:
        - JOB=swiftpm-mac
